// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB43t3wcYdC1LK2GTKbNIIYENAWHTZLMXM',
    appId: '1:750394725557:web:7127fdaaf2ff340dbddafc',
    messagingSenderId: '750394725557',
    projectId: 'my-notes-app-65ac3',
    authDomain: 'my-notes-app-65ac3.firebaseapp.com',
    storageBucket: 'my-notes-app-65ac3.appspot.com',
    measurementId: 'G-6E8NXKCMW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwCiOG4uvxGPvdweuPGZt2_sBYKV6XiiU',
    appId: '1:750394725557:android:d0ab9981596dcf22bddafc',
    messagingSenderId: '750394725557',
    projectId: 'my-notes-app-65ac3',
    storageBucket: 'my-notes-app-65ac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmNc8z5jviZLDrhtQqBoQ339tYGD6GpC8',
    appId: '1:750394725557:ios:92130d47f4359da1bddafc',
    messagingSenderId: '750394725557',
    projectId: 'my-notes-app-65ac3',
    storageBucket: 'my-notes-app-65ac3.appspot.com',
    iosClientId: '750394725557-rfccim2k9l0t4t0far0fqfoo2srvdvjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmNc8z5jviZLDrhtQqBoQ339tYGD6GpC8',
    appId: '1:750394725557:ios:92130d47f4359da1bddafc',
    messagingSenderId: '750394725557',
    projectId: 'my-notes-app-65ac3',
    storageBucket: 'my-notes-app-65ac3.appspot.com',
    iosClientId: '750394725557-rfccim2k9l0t4t0far0fqfoo2srvdvjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
